name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # runs daily
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Create output directory
        run: mkdir -p dist

      - name: Generate the snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: iitian360
          svg_out_path: dist/github-contribution-grid-snake.svg
          gif_out_path: dist/github-contribution-grid-snake.gif

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
